### ISSUE TITLE
Vertical viewport was given unbounded height. 

### ISSUE THREAD

**Issue by easysoft-mobility** [mohamed-selim-a/ResponsiveGrid_Flutter#5]
My **ResponsiveGridList** need to be inside a listview so I get this error:

""Exception caught by rendering library
The following assertion was thrown during performResize():
Vertical viewport was given unbounded height."

The usual solution is to add property shrinkWrap=true to the widget but **ResponsiveGridList** does'nt recognize this property

**Comment by muhammad369** [comment]
This exception is thrown because the *ResponsiveGridList* is a list that has a scroll (unbounded height), so it it can't be placed inside another unbounded height,

For this reason I've implemented the 'scroll' property (from version 1.1.0) which you can set to 'false',so the *ResponsiveGridList* will be rendered as a *Column* not a *List*
