### ISSUE TITLE
Placing a single child of row in center 

### ISSUE THREAD

**Issue by AliYar-Khan** [mohamed-selim-a/ResponsiveGrid_Flutter#6]
Need help in placing on child of Row which is a col to be in center in row. In Bootstrap there is some classes like "row align-items-center" and "col align-items-center". How i can achieve this !

**Comment by muhammad369** [comment]
place the item inside 'Center' Widget

**Comment by codegrue** [comment]
This also applies to any number of items that don't fit on a row. I have 1000px of horizontal space and two items that are 300px each, they appear left-justified instead of centered.

``` dart
return ResponsiveGridList(
  desiredItemWidth: 300,
  minSpacing: 10,
  children: [
    profilePanel,
    accountPanel,
  ],
);
```

<img width="806" alt="Screen Shot 2020-06-12 at 4 28 49 PM" src="https://user-images.githubusercontent.com/2914616/84543693-d6c72200-acc9-11ea-90c8-fdd97c887212.png">

Note: "inside 'Center' Widget" doesn't work because ResponsiveGridList expands to take up all available space.

**Comment by muhammad369** [comment]
excuse me for the so late response
use version 1.2.0 
and set the ResponsiveGridList property rowMainAxisAlignment to center
```
return ResponsiveGridList(
        rowMainAxisAlignment: MainAxisAlignment.center,
```
